let slideIndex = 0;
showSlides();
let playText = false;
let textIndex=0;
const text=['COMPRA TUS SUEÑOS' ,
    ' Y sueña con lo que te vendo,' ,
    ' ya nadie pinta si no es en 4k.' ,
    '' ,
    'MENOS NUNCA SERA MAS' ,
    '' ,
    'Trabaja duro y serás el REY ¡TODOS VOSOTROS SERÉIS REYES!' ,
    ' Solo tienes que aplastar a los demás,' ,
    ' COMPITE, compite con EFICIENCIA,' ,
    ' se productivo, estudia otro máster,' ,
    ' y PRODUCE constantemente al ritmo de Instagram,' ,
    ' se ingenioso,' ,
    ' creativo y AUTÓNOMO.' ,
    'Ofrécenos lo mejor de ti ' ,
    ' y ganaras ' ,
    ' GANA,' ,
    ' GANA' ,
    ' Y GANA nuestra nueva libertad virtual.' ,
    '' ,
    'Estas son las promesas de los corderos del capital,' ,
    ' Dios supremo del egoísmo' ,
    ' agnóstico y apolítico' ,
    ' que hasta el arte ha podido patrimonializar.' ,
    '' ,
    'Somos la generación mas prolífica y preparada artísticamente,' ,
    ' gracias a la ultra comunicación e Internet' ,
    ' tenemos un bagaje visual y cultural que ni Warhol con sus viajes,' ,
    ' sin embargo vivimos en un estado constante de estrés' ,
    ' de consumo obsesivo-compulsivo' ,
    ' que no nos permite retener,' ,
    ' entender,' ,
    ' disfrutar' ,
    ' ni retozar...' ,
    ' esclavos de la tendencia,' ,
    ' la frustración' ,
    ' y la inseguridad.' ,
    '' ,
    'EL PUTO MUNDO ESTÁ LLENO' ,
        'EL PUTO MUNDO ESTÁ LLENO' ,
        'EL PUTO MUNDO ESTÁ LLENO' ,
        'EL PUTO MUNDO ESTÁ LLENO' ,
        'EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO ' ,
        'EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO ' ,
        'EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO ' ,
        'EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO ' ,
        'EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO EL PUTO MUNDO ESTÁ LLENO' ,
        '',
        '',
    'Todo esta hecho ya,' ,
    ' no hay necesidad de crear...' ,
    ' solo destruir,' ,
    ' deconstruir,' ,
    ' redefinir,' ,
    ' descubrir,' ,
    ' morir' ,
    ' y' ,
    'volver a empezar...' ,
    '' ,
    '' ,
    '"Nosotros hemos inventado la felicidad"' ,
    ' -dicen los últimos hombres, y parpadean.' ,
    'F. Nietzsche' ,
    '' ,
    '' ,
    'NON PLUS ULTRA' ,
    '' ,
    'Y que Tzara me perdone' ,
    ' pero vengo a gritar mi A,B,C' ,
    ' con sus nuevos y pequeños a,b,c’s.' ,
    'La única novedad' ,
    ' es que ya no hay novedad' ,
    ' solo anuncios en fullHD.' ,
    '' ,
    'Nunca seremos pioneras' ,
    ' como Picasso o Basquiat,' ,
    ' las cámaras de bolsillo retratan mejor que tu,' ,
    ' Bacon ya hizo lo del psicoretrato,' ,
    ' hemos combinado manchas absurdas de colores' ,
    ' de todas las formas aleatorias posibles,' ,
    ' no tendremos nunca la delicadeza de Monet,' ,
    ' ni el dominio de Velázquez' ,
    ' ni la blanca polla de Goya...' ,
    '' ,
    '' ,
    'LOS VIEJOS ÍDOLOS ESTÁN PODRIDOS' ,
    'son los bastiones de viejos' ,
    ' hombres muy machos' ,
    ' y rancios,' ,
    ' no más Picasso,' ,
    ' no más Marley,' ,
    ' no mas Gandhi,' ,
    ' murióse ya Cela,' ,
    ' Toulouse-Lautrec era mas feo por dentro que por fuera' ,
    ' ¡apropiémonos de su legado y quememos su recuerdo! ' ,
    '¡Nosotras hemos evolucionado! ' ,
    'Hay que Trascender el pasado, este no puede ser una losa en nuestra...' ,
    'DECONSTRUCCIÓN.' ,
        'DECONSTRUCCIÓN.' ,
        'DECONSTRUCCIÓN.' ,
    '' ,
        '' ,
        '' ,
        '' ,
        '' ,
    'Nosotras no queremos competir,' ,
    ' nosotras no queremos ganar en un juego asesino,' ,
    ' no necesitamos lienzos de algodón para pintar,' ,
    ' no hace falta hipotecarse en ninguna bella universidad,' ,
    ' ser artista no debe ser un privilegio blanco y bienestante,' ,
    ' ser artista no es un don divino, todas nacemos creadoras.' ,
    '' ,
    'Tampoco somos militantes,' ,
    ' ya no hay lucha ni clase ninguna,' ,
    ' tan privilegiados como oprimidas y desganadas,' ,
    ' ya nacimos cansadas,' ,
    ' solo vamos a yacer para ver al sol salir.' ,
    ' No queremos pastar con su rebaño,' ,
    ' no somos datos de su IAlgoritmo ni estamos optimizadas.' ,
    ' Somos caos,' ,
    ' viento' ,
    ' y pasión,' ,
    ' somos el fuego que quema el viejo bosque,' ,
    ' húmedo oscuro y podrido,' ,
    ' el aquelarre de las almas que ya no obedecen jamas,' ,
    ' no nos perdones Dios porque sabemos lo que nos hacemos.' ,
    '' ,
    '' ,
    'TRANS_DADA' ,
    'Ahora somos inclusivas, combativas,' ,
    ' cargadas de odio rabia y alegría.' ,
    ' No es solo la erudita e intelectual negación vanguardista,' ,
    ' no somos tan puras ni ilustradas como los viejos dadaístas,' ,
    ' ni nos importa,' ,
    ' devolvamos el arte a la gente.' ,
    ' Basta de Elitismo,' ,
    ' el arte sea figurativo, sea abstracto, expresionista o pop,' ,
    ' juegue con la estética y retuerza la tendencia,' ,
    ' o sea el torrido sueño de un médium sin conciencia...' ,
    'pero... el ARTE NO ES DECORATIVO' ,
    '' ,
    'ARTISNOTCASH' ,
    '' ,
    'PORQUÉ EL ARTE DEBE SER ESTANDARTE,' ,
    'El dedo que señala el camino de nuevas visiones,' ,
    ' el PENSAMIENTO CRÍTICO que nadie puede todavía verbalizar.' ,
    'La obiedad que me siento obligada a reiterar.' ,
    ' Antes que la FILOSOFÍA y el ACTIVISMO apunten nuevas respuestas,' ,
    ' el arte hizo las preguntas,' ,
    ' tal es el gran poder de las artistas en la humanidad,' ,
    ' no abandonemos tal responsabilidad ' ,
    'por los triviales éxitos que promete el capital.' ,
    '' ,
    'POR ESO ESTAMOS EN GUERRA,' ,
    ' CONTRA LOS MALOS VICIOS DEL PASADO' ,
    ' CONTRA LAS EXPECTATIVAS,' ,
    ' CONTRA EL EXITO' ,
    ' CONTRA SUS ANQUILOSADAS CONVENCIONES NATURALES,' ,
    ' en guerra no hay ley,' ,
    ' venimos para quemar todos los pilares y prostituir toda seriedad.' ,
    '  Y no tendremos ninguna compasión.' ,
    '' ,
    'Huyendo de lo aprendido y deconstruyendo nuestra filosofía,' ,
    ' nos hemos acabado viendo a nosotras mismas,' ,
    ' y nosotras solo queremos pintar,' ,
    ' bailar, gritar, esculpir y escupir.' ,
    'Nos gusta la sangre y la madera,' ,
    ' no sabemos de títulos, escuelas ni presupuestos,' ,
    ' queremos pintar oleo en sus pantallas amoled,' ,
    ' potaremos en su smart diseño,' ,
    ' nos gusta el polvo y el óxido en sus chasis de acero,' ,
    ' vale tudo en la batalla. ' ,
    'Porque el arte es un torrente expresivo' ,
    ' imparable e innato,' ,
    ' liberemos el arte de las galerías' ,
    ' y las redes,' ,
    ' salvemos a las artistas de la €$clavitud!' ,
    '' ,
    'No es una cuestión de estilo,' ,
    ' no es una nueva perspectiva' ,
    ' ni una prodigiosa síntesis primitivista,' ,
    ' es una actitud,' ,
    ' es saber que somos' ,
    ' las ANARQUISTAS QUE NUNCA HAN LEÍDO A BAKUNIN,' ,
    ' somos el “HOMBRE” más allá del género,' ,
    ' más allá de toda ley o credo,' ,
    ' las portadoras del virus de la LIBERTAD y la inhibición,' ,
    ' agentes del caos artístico,' ,
    ' como decía el buen Tristán:' ,
    ' Yo hablo por mí, no quiero arrastrar a nadie a mi rio...' ,
    'pero si como yo sientes estos corsés que cohíben tu expresión artística,' ,
    ' estas ganas de gritar y destruir las cadenas del bagaje,' ,
    ' si ,como yo, solo quieres pintar fuerte y claro,' ,
    ' haz tuyo este manifiesto,' ,
    ' dale la vuelta,' ,
    ' llama a tus obras TRASH ART' ,
    ' y defínete así si gusta,' ,
    ' no dejes que nadie te diga que no puedes,' ,
    ' difunde los conceptos del TRASH ART' ,
    ' y su palabra de gozo y destrucción' ,
    ' y sobre todo...' ,
    '' ,
    'Pinta,' ,
    ' Rompe ideas, conceptos y cánones,' ,
    ' compón iracundas celebraciones' ,
    ' de asexuada promiscuidad,' ,
    ' embriágate de la contradicción' ,
    ' y comparte la...' ,
    'DECONS(DES)TRUCCIÓN!' ,
    '' ,
    'WE ART TERRORISTS' ,
    'Y esta es mi guerra,' ,
    ' contra el esclavismo publicitario,' ,
    ' contra la competitividad,' ,
    ' contra las galerías y mercados,' ,
    ' contra el aburrido sueño europeo,' ,
    ' contra el cruel racionalismo económico y su lógica' ,
    ' que menosprecia la libertad creativa' ,
    ' y bloquea la inspiración con su constante competición.' ,
    ' Contra todo normativismo' ,
    ' se alza este manifiesto Transdadaísta.' ,
    ' El viejo Dada y las vanguardias ya no sirven,' ,
    ' murieron roídas e incomprendidas en lejanos museos,' ,
    ' no despiertan ya la libertad creativa que pretendían,' ,
    ' ensimismadas en la pulcritud de sus técnicas ' ,
    ' hoy ya tan lejanas y elitistas...' ,
    '' ,
    'No necesitas saber que es DADA.' ,
    ' Tu arte no tiene por qué ser bella,' ,
    ' no necesitas más que sentir la libertad creativa' ,
    ' y por ella dejarte guiar,' ,
    ' consciente o inconscientemente,' ,
    ' con las influencias y estéticas que quieras,' ,
    ' usa los clichés a tu merced,' ,
    ' que no sean ellos quienes te limiten a ti,' ,
    ' debemos ser terroristas del arte,' ,
    ' detectar las bases de este sistema' ,
    ' de pensamiento caduco y dinamitarlo' ,
    ' con el odio de las oprimidas,' ,
    ' convirtamos esa rabia en pura tinta y sangre' ,
    ' con la que envenenar sus cerebros temerosos...' ,
    '' ,
    'Esta pura intención crítica,' ,
    ' pícara y sornosa será nuestra seña,' ,
    ' la libertad y sinceridad artística nuestras musas.' ,
    '' ,
    'TRASH' ,
    ' es el odio y la rabia del activismo que te hizo despertar...' ,
    'TRASH ' ,
    ' es el martillo nihilista del NO.' ,
    'TRASH ' ,
    ' es la escoria que no quiere reinar' ,
    'TRASH son las niñas que solo quieren pintar' ,
    'TRASH es deconstrucción, destrucción,' ,
    'mutilación y exacerbación de la realidad, es' ,
    'la negación del todo y sus cuerdas...' ,
    'TRASH es Shiva arrasando la creación.' ,
    'TRASH es la lucha por la vida.' ,
    'TRASH es el el ataque como mejor defensa.' ,
    'TRASH es autodefensa artística' ,
    'TRASH es celebración de nuestra identidad' ,
    'TRASH es inconformismo hilarante' ,
    'TRASH es la perversión del DADA' ,
    '' ,
    'Recuperemos la libre y ancestral inspiración,' ,
    ' la santa intuición, recuperemos la libertad,' ,
    ' la inocencia primigenia olvidada,' ,
    ' recuperemos el arte...' ,
    ' Regurgitemos el alma en cada verso' ,
    ' descarnando el lienzo sin miedo' ,
    '¡Faire l’art pour le plaisir de faire Art!' ,
    '' ,
    'Y a ti nadie te volverá a silenciar.' ,
    '' ,
    'Porque TRASH eres TU...' ,
    ''
]
const playBtn = document.querySelector(".play");

const manifestBtn = document.querySelector(".manifest-btn");
function showSlides() {
    let i;
    let slides = document.getElementsByClassName("mySlides");
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}
    slides[slideIndex-1].style.display = "block";
    setTimeout(showSlides, 3500); // Change image every 2 seconds
}

const consoleOut = document.querySelector('.console');

const outputMessage = function (str) {
    const mssg = `</br> &gt; ${str}`
    consoleOut.insertAdjacentHTML("beforeend", mssg);
    consoleOut.scroll(0, consoleOut.scrollHeight);
}
playBtn.addEventListener('click', () => {
    playText= !playText;
    playText?playBtn.textContent="Pause":playBtn.textContent="Play";}
);
const startManifest=function (){
    textIndex=0;
    playText= true;
    consoleOut.scrollIntoView();
    playBtn.textContent="Pause"}

const setTimer = function () {
    setTimeout(() => {
        if(playText===true){
            outputMessage(text[textIndex]);
            textIndex++;
        }
        if(textIndex<text.length){setTimer();}
        else{
            textIndex=0;
            playText= false;
            playBtn.textContent="Play"
        }
    }, 1200);
}
setTimer();